name: Deploy EC2 Dev

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "$DEV_EC2_SSH_KEY" > devops-key
          chmod 600 devops-key

      - name: Upload logs to S3 from EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i devops-key ubuntu@13.235.134.40 '
            bash ~/test-repo-for-devops/scripts/upload_logs.sh dev
          '
        env:
          DEV_EC2_SSH_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
